---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: commandes-app
  namespace: default
  labels:
    app: commandes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commandes-app
  template:
    metadata:
      labels:
        app: commandes-app
    spec:
      containers:
      - name: commandes-app
        image: "enoch180/commandes:1.0"
        ports:
          - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: commandes-app
  namespace: default
spec:
  selector:
    app: commandes-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 4001
    port: 81
